Repository jupyterhub/batchspawner, pull requests merged in 2024-03, with the labels that each got.

#301 TST: don't assume test user is OS user
  batchspawner/tests/test_spawners.py
Labels: maintenance

#256 Fix Slurm test used regular expression
  batchspawner/tests/test_spawners.py
Labels: maintenance

#265 Remove `which jupyterhub-singleuser` command from `SlurmSpawner.batch_script`
  batchspawner/batchspawner.py
Labels: bug

#219 Improve submit_batch_script logging
  batchspawner/batchspawner.py
Labels: maintenance

#302 Add changelog for v1.3.0
  CHANGELOG.md
  README.md
Labels: documentation

#254 poll job status while waiting for single-user server to be reachable
  batchspawner/batchspawner.py
  batchspawner/tests/test_spawners.py
Labels: bug
